### ISSUE TITLE
update require of ipc

### ISSUE THREAD

**Issue by aaronfrost** [develar/electron-updater#41]
Because electron updater has a `require("ipc")` call, every one who uses it will get a message in their console like this:

![image](https://cloud.githubusercontent.com/assets/662832/11833379/27ac4f78-a37f-11e5-84f8-2f410e10eab7.png)

We should update the call to `require('electron').ipcMain;` to get rid of the warning in the console.

**Comment by yuxizhe** [comment]
same problem

**Comment by develar** [comment]
Project on NPM since version 1.0.0 is a part of [electron-builder](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater).
