### ISSUE TITLE
Pass old and new versions into the `updateAvailable`

### ISSUE THREAD

**Issue by aaronfrost** [develar/electron-updater#42]
Having the old and new version passing into the `updateAvailable` callback would allow the consumers of electron-updater to react differently to a patch update verses a minor or major update. 

In some cases, you may want to only request that the user update. In others, you may want to prevent them from using the app until the user updates. These kinds of things would be enabled if we passed those versions into the updateAvailable callback.

**Comment by develar** [comment]
Project on NPM since version 1.0.0 is a part of [electron-builder](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater).
