### ISSUE TITLE
Add documentation for semver syntax and how it affects updater

### ISSUE THREAD

**Issue by aaronfrost** [develar/electron-updater#43]
Because electron-updater will watch each of the dependencies listed in `package.dependencies`, people will likely want to avoid using the carrot in their semver. An example: instead of `"angular": "^1.4.7"` you will want to use `"angular": "1.4.7"`, without the carrot. 

Add the section to the documentation that when switching from using the carrot to not using the carrot, make sure and run `npm outdated` to get a list of the outdated deps in their `package.dependencies`. Then update their semvers with the versions listed in the `outdated` call. @justinmchase and I ran into an issue with this, and likely more people will.

**Comment by develar** [comment]
Project on NPM since version 1.0.0 is a part of [electron-builder](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater).
