### ISSUE TITLE
Add blurb to doc about "Must Have Error Callback"

### ISSUE THREAD

**Issue by aaronfrost** [develar/electron-updater#46]
If you don't have an `updater.on('error', fn)` listener, all errors from the updater will bubble to the end users. Modify the documentation to include an explanation of this behavior. You must have the error handler, even if it is empty, it just has to exist.

**Comment by develar** [comment]
Project on NPM since version 1.0.0 is a part of [electron-builder](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater).
