### ISSUE TITLE
Add note for required npm to build and pack electron-updater

### ISSUE THREAD

**Issue by Vj3k0** [develar/electron-updater#51]
Pack it with npm 2 / Node v0.12.x.
I wrote about it here: 
http://electron.rocks/problem-with-bundleddependencies-2/

**Comment by justinmchase** [comment]
Interesting, I'll look into it.

**Comment by justinmchase** [comment]
Related: https://github.com/npm/npm/issues/9175

**Comment by develar** [comment]
Project on NPM since version 1.0.0 is a part of [electron-builder](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater).
