### ISSUE TITLE
How to solve the "permission denied"  problem? 

### ISSUE THREAD

**Issue by yuxizhe** [develar/electron-updater#56]
When I use the "sudo npm start" command,the app can update . But when I use "npm start",update is denied.  Maybe other user don't want to use the "sudo" command, they don't want to type the password.  
Is it necessary to use the root user to update the app? How can I avoid typing password?

**Comment by justinmchase** [comment]
It shouldn't be necessary no. It does however, depend on the permissions of the various folders you're trying to update.

I'm assuming your on osx?

**Comment by yuxizhe** [comment]
Yes, I use the OSX

**Comment by thatikuntap** [comment]
below worked for me on OS X
git clone https://github.com/EvolveLabs/electron-updater.git

**Comment by develar** [comment]
Project on NPM since version 1.0.0 is a part of [electron-builder](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater).
