### ISSUE TITLE
Should check if app is online before checking/updating.

### ISSUE THREAD

**Issue by Phillips126** [develar/electron-updater#58]
I'm currently working on an Electron application that will be primarily online, but occasionally offline when out in the field.  The updater does not seem to handle offline well - especially if there is a pending update.

I'm looking into patching this feature in, but if you have any tips or thoughts, please share!

**Comment by justinmchase** [comment]
Feel free, PR's welcome.

**Comment by develar** [comment]
Project on NPM since version 1.0.0 is a part of [electron-builder](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater).
