### ISSUE TITLE
I am getting below error after app update

### ISSUE THREAD

**Issue by shahidmau** [develar/electron-updater#64]
Thanks for awesome work :)

Kindly help on below error.
------------------------------------------------
Starting...
Update is pending, exiting...
execPath:/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron
copy appDir: /usr/local/lib/node_modules/electron/dist/Electron.app
  updateDir: /Users/apple/Library/Application Support/my-support-app2/updater/1.4.15
{ Error: ENOTDIR: not a directory, stat '/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/default_app.js'
    at Error (native)
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'stat',
  path: '/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/default_app.js' }
errr
{ Error: ENOTDIR: not a directory, stat '/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/default_app.js'
    at Error (native)
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'stat',
  path: '/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/default_app.js' }

**Comment by develar** [comment]
It seems you are trying use update not for packed app, but using `electron` (dev mode), right?
